### ISSUE TITLE
compiles failes, Could not find rake-12.3.2 in any of the sources

### ISSUE THREAD

**Issue by hopewise** [stve/capistrano-local-precompile#35]
Although rake 12.3.2 is installed, I get this error:
```
Compiling...
Compilation failed:
/home/samir/.rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/bundler/spec_set.rb:86:in `block in materialize': Could not find rake-12.3.2 in any of the sources (Bundler::GemNotFound)
```
how to debug where it does search for it??

full error:

```
The deploy has failed with an error: rake exit status: 256
rake stdout: I, [2020-04-14T19:42:51.309079 #15705]  INFO -- sentry: ** [Raven] Raven 3.0.0 ready to catch errors
Compiling...
Compilation failed:
/home/samir/.rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/bundler/spec_set.rb:86:in `block in materialize': Could not find rake-12.3.2 in any of the sources (Bundler::GemNotFound)
        from /home/samir/.rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/bundler/spec_set.rb:80:in `map!'
        from /home/samir/.rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/bundler/spec_set.rb:80:in `materialize'
        from /home/samir/.rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/bundler/definition.rb:170:in `specs'
        from /home/samir/.rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/bundler/definition.rb:237:in `specs_for'
        from /home/samir/.rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/bundler/definition.rb:226:in `requested_specs'
        from /home/samir/.rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:101:in `block in definition_method'
        from /home/samir/.rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:20:in `setup'
        from /home/samir/.rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/bundler.rb:149:in `setup'
        from /home/samir/.rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/bundler/setup.rb:20:in `block in <top (required)>'
        from /home/samir/.rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/bundler/ui/shell.rb:136:in `with_level'
        from /home/samir/.rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/bundler/ui/shell.rb:88:in `silence'
        from /home/samir/.rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/bundler/setup.rb:20:in `<top (required)>'
        from /home/samir/.rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        from /home/samir/.rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:92:in `require'
rake stderr: NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /home/samir/.rvm/gems/ruby-2.5.1/specifications/libv8-3.16.14.19-x86_64-linux.gemspec:17.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /home/samir/.rvm/gems/ruby-2.5.1/specifications/libv8-3.16.14.19-x86_64-linux.gemspec:17.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /home/samir/.rvm/gems/ruby-2.5.1/specifications/cancan-1.6.10.gemspec:15.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /home/samir/.rvm/gems/ruby-2.5.1/specifications/coffee-script-source-1.12.2.gemspec:16.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /home/samir/.rvm/gems/ruby-2.5.1/specifications/orm_adapter-0.5.0.gemspec:16.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /home/samir/.rvm/gems/ruby-2.5.1/specifications/warden-1.2.8.gemspec:18.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /home/samir/.rvm/gems/ruby-2.5.1/specifications/formatador-0.2.5.gemspec:18.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /home/samir/.rvm/gems/ruby-2.5.1/specifications/erubis-2.7.0.gemspec:17.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /home/samir/.rvm/gems/ruby-2.5.1/specifications/font_assets-0.1.14.gemspec:15.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /home/samir/.rvm/gems/ruby-2.5.1/specifications/gravtastic-3.2.6.gemspec:15.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /home/samir/.rvm/gems/ruby-2.5.1/specifications/omniauth-auth0-1.4.2.gemspec:16.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /home/samir/.rvm/gems/ruby-2.5.1/specifications/rack-proxy-0.6.5.gemspec:15.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /home/samir/.rvm/gems/ruby-2.5.1/specifications/sprockets-3.7.2.gemspec:19.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /home/samir/.rvm/gems/ruby-2.5.1/specifications/routing-filter-0.6.3.gemspec:16.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /home/samir/.rvm/gems/ruby-2.5.1/specifications/ruby-debug-ide-0.7.0.gemspec:21.
config.eager_load is set to nil. Please update your config/environments/*.rb files accordingly:

  * development - set it to false
  * test - set it to false (unless you use a tool that preloads your test environment)
  * production - set it to true

```

**Comment by hopewise** [comment]
Solved it, I found that it was searching for rake into vendor/bundle, so I 

    bundle install --path vendor/bundle
