### ISSUE TITLE
manifest.json

### ISSUE THREAD

**Issue by hootan-nikbakht** [stve/capistrano-local-precompile#8]
This gem definitely, solved my problem in precompiling my assets with same fingerprinting to be deployed to multiple instances of app server code. I am however seeing a side effect when trying to redeploy by seeing the following exception: 

``` text
`parse': (<unknown>): mapping values are not allowed in this context at line 1 column 13 (Psych::SyntaxError)
    from /Users/hootan/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/2.0.0/psych.rb:205:in `parse_stream'
    from /Users/hootan/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/2.0.0/psych.rb:153:in `parse'
    from /Users/hootan/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/2.0.0/psych.rb:129:in `load'
    from /Users/hootan/.rvm/gems/ruby-2.0.0-p451@global/gems/capistrano-2.15.5/lib/capistrano/recipes/deploy/assets.rb:26:in `parse_manifest'
    from /Users/hootan/.rvm/gems/ruby-2.0.0-p451@global/gems/capistrano-2.15.5/lib/capistrano/configuration/namespaces.rb:191:in `method_missing'
    from /Users/hootan/.rvm/gems/ruby-2.0.0-p451@global/gems/capistrano-2.15.5/lib/capistrano/configuration/namespaces.rb:191:in `method_missing'
    from /Users/hootan/.rvm/gems/ruby-2.0.0-p451@global/gems/capistrano-2.15.5/lib/capistrano/recipes/deploy/assets.rb:93:in `block (3 levels) in load'
    from /Users/hootan/.rvm/gems/ruby-2.0.0-p451@global/gems/capistrano-2.15.5/lib/capistrano/configuration/execution.rb:138:in `instance_eval'
    from /Users/hootan/.rvm/gems/ruby-2.0.0-p451@global/gems/capistrano-2.15.5/lib/capistrano/configuration/execution.rb:138:in `invoke_task_directly'
    from /Users/hootan/.rvm/gems/ruby-2.0.0-p451@global/gems/capistrano-2.15.5/lib/capistrano/configuration/callbacks.rb:25:in `invoke_task_directly_with_callbacks'
    from /Users/hootan/.rvm/gems/ruby-2.0.0-p451@global/gems/capistrano-2.15.5/lib/capistrano/configuration/execution.rb:89:in `execute_task'
    from /Users/hootan/.rvm/gems/ruby-2.0.0-p451@global/gems/capistrano-2.15.5/lib/capistrano/configuration/execution.rb:101:in `find_and_execute_task'
    from /Users/hootan/.rvm/gems/ruby-2.0.0-p451@global/gems/capistrano-2.15.5/lib/capistrano/callback.rb:38:in `call'
    from /Users/hootan/.rvm/gems/ruby-2.0.0-p451@global/gems/capistrano-2.15.5/lib/capistrano/configuration/callbacks.rb:141:in `block in trigger'
    from /Users/hootan/.rvm/gems/ruby-2.0.0-p451@global/gems/capistrano-2.15.5/lib/capistrano/configuration/callbacks.rb:141:in `each'
    from /Users/hootan/.rvm/gems/ruby-2.0.0-p451@global/gems/capistrano-2.15.5/lib/capistrano/configuration/callbacks.rb:141:in `trigger'
    from /Users/hootan/.rvm/gems/ruby-2.0.0-p451@global/gems/capistrano-2.15.5/lib/capistrano/configuration/callbacks.rb:23:in `invoke_task_directly_with_callbacks'
    from /Users/hootan/.rvm/gems/ruby-2.0.0-p451@global/gems/capistrano-2.15.5/lib/capistrano/configuration/execution.rb:89:in `execute_task'
    from /Users/hootan/.rvm/gems/ruby-2.0.0-p451@global/gems/capistrano-2.15.5/lib/capistrano/configuration/execution.rb:101:in `find_and_execute_task'
    from /Users/hootan/.rvm/gems/ruby-2.0.0-p451@global/gems/capistrano-2.15.5/lib/capistrano/callback.rb:38:in `call'
    from /Users/hootan/.rvm/gems/ruby-2.0.0-p451@global/gems/capistrano-2.15.5/lib/capistrano/configuration/callbacks.rb:141:in `block in trigger'
    from /Users/hootan/.rvm/gems/ruby-2.0.0-p451@global/gems/capistrano-2.15.5/lib/capistrano/configuration/callbacks.rb:141:in `each'
    from /Users/hootan/.rvm/gems/ruby-2.0.0-p451@global/gems/capistrano-2.15.5/lib/capistrano/configuration/callbacks.rb:141:in `trigger'
    from /Users/hootan/.rvm/gems/ruby-2.0.0-p451@global/gems/capistrano-2.15.5/lib/capistrano/configuration/callbacks.rb:27:in `invoke_task_directly_with_callbacks'
    from /Users/hootan/.rvm/gems/ruby-2.0.0-p451@global/gems/capistrano-2.15.5/lib/capistrano/configuration/execution.rb:89:in `execute_task'
    from /Users/hootan/.rvm/gems/ruby-2.0.0-p451@global/gems/capistrano-2.15.5/lib/capistrano/configuration/namespaces.rb:191:in `method_missing'
    from /Users/hootan/.rvm/gems/ruby-2.0.0-p451@global/gems/capistrano-2.15.5/lib/capistrano/configuration/namespaces.rb:110:in `block in define_task'
    from /Users/hootan/.rvm/gems/ruby-2.0.0-p451@global/gems/capistrano-2.15.5/lib/capistrano/recipes/deploy.rb:234:in `block (3 levels) in load'
    from /Users/hootan/.rvm/gems/ruby-2.0.0-p451@global/gems/capistrano-2.15.5/lib/capistrano/configuration/execution.rb:56:in `transaction'
    from /Users/hootan/.rvm/gems/ruby-2.0.0-p451@global/gems/capistrano-2.15.5/lib/capistrano/configuration/namespaces.rb:191:in `method_missing'
    from /Users/hootan/.rvm/gems/ruby-2.0.0-p451@global/gems/capistrano-2.15.5/lib/capistrano/recipes/deploy.rb:233:in `block (2 levels) in load'
    from /Users/hootan/.rvm/gems/ruby-2.0.0-p451@global/gems/capistrano-2.15.5/lib/capistrano/configuration/execution.rb:138:in `instance_eval'
    from /Users/hootan/.rvm/gems/ruby-2.0.0-p451@global/gems/capistrano-2.15.5/lib/capistrano/configuration/execution.rb:138:in `invoke_task_directly'
    from /Users/hootan/.rvm/gems/ruby-2.0.0-p451@global/gems/capistrano-2.15.5/lib/capistrano/configuration/callbacks.rb:25:in `invoke_task_directly_with_callbacks'
    from /Users/hootan/.rvm/gems/ruby-2.0.0-p451@global/gems/capistrano-2.15.5/lib/capistrano/configuration/execution.rb:89:in `execute_task'
    from /Users/hootan/.rvm/gems/ruby-2.0.0-p451@global/gems/capistrano-2.15.5/lib/capistrano/configuration/namespaces.rb:191:in `method_missing'
    from /Users/hootan/.rvm/gems/ruby-2.0.0-p451@global/gems/capistrano-2.15.5/lib/capistrano/configuration/namespaces.rb:110:in `block in define_task'
    from /Users/hootan/.rvm/gems/ruby-2.0.0-p451@global/gems/capistrano-2.15.5/lib/capistrano/recipes/deploy.rb:201:in `block (2 levels) in load'
    from /Users/hootan/.rvm/gems/ruby-2.0.0-p451@global/gems/capistrano-2.15.5/lib/capistrano/configuration/execution.rb:138:in `instance_eval'
    from /Users/hootan/.rvm/gems/ruby-2.0.0-p451@global/gems/capistrano-2.15.5/lib/capistrano/configuration/execution.rb:138:in `invoke_task_directly'
    from /Users/hootan/.rvm/gems/ruby-2.0.0-p451@global/gems/capistrano-2.15.5/lib/capistrano/configuration/callbacks.rb:25:in `invoke_task_directly_with_callbacks'
    from /Users/hootan/.rvm/gems/ruby-2.0.0-p451@global/gems/capistrano-2.15.5/lib/capistrano/configuration/execution.rb:89:in `execute_task'
    from /Users/hootan/.rvm/gems/ruby-2.0.0-p451@global/gems/capistrano-2.15.5/lib/capistrano/configuration/execution.rb:101:in `find_and_execute_task'
    from /Users/hootan/.rvm/gems/ruby-2.0.0-p451@global/gems/capistrano-2.15.5/lib/capistrano/cli/execute.rb:46:in `block in execute_requested_actions'
    from /Users/hootan/.rvm/gems/ruby-2.0.0-p451@global/gems/capistrano-2.15.5/lib/capistrano/cli/execute.rb:45:in `each'
    from /Users/hootan/.rvm/gems/ruby-2.0.0-p451@global/gems/capistrano-2.15.5/lib/capistrano/cli/execute.rb:45:in `execute_requested_actions'
    from /Users/hootan/.rvm/gems/ruby-2.0.0-p451@global/gems/capistrano-2.15.5/lib/capistrano/cli/help.rb:19:in `execute_requested_actions_with_help'
    from /Users/hootan/.rvm/gems/ruby-2.0.0-p451@global/gems/capistrano-2.15.5/lib/capistrano/cli/execute.rb:34:in `execute!'
    from /Users/hootan/.rvm/gems/ruby-2.0.0-p451@global/gems/capistrano-2.15.5/lib/capistrano/cli/execute.rb:14:in `execute'
    from /Users/hootan/.rvm/gems/ruby-2.0.0-p451@global/gems/capistrano-2.15.5/bin/cap:4:in `<top (required)>'
    from /Users/hootan/.rvm/rubies/ruby-2.0.0-p451/bin/cap:23:in `load'
    from /Users/hootan/.rvm/rubies/ruby-2.0.0-p451/bin/cap:23:in `<main>'
```

I removed manifest-<hash>.json from app/shared/assets folder and the redeploy works fine, but this is not practical to login to every single instance and remove. Is this a known problem ? please help.

**Comment by steakchaser** [comment]
This error occurs in `:update_asset_mtimes` if there is more than 1 manifest*.json in the `shared_path/shared_assets_prefix`.  The above fix should remove the manifest from this location instead.  

I think we should change to:
```ruby
    desc "remove manifest file from remote server"
    task :remove_manifest, roles: :web do
      run "rm -f #{shared_path}/#{shared_assets_prefix}/manifest*.json"
    end
```

**Comment by stve** [comment]
Thanks @steakchaser, would you mind submitting a pull request?

**Comment by nozpheratu** [comment]
+1
@stve Have you had a chance to take a look at the PR from @steakchaser ?

**Comment by nozpheratu** [comment]
Nevermind. It looks like @steakchaser did submit that PR after all. The gem just hasn't been updated on rubygems.
